logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "apk"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
excluded-patches = "'Enable debugging' 'Old video quality menu' 'Disable fine scrubbing gesture' 'External downloads' 'Enable tablet layout' 'Premium heading' 'Comments' 'Wide searchbar' 'Alternative thumbnails' 'Spoof app version' 'Custom player overlay opacity' 'Theme' 'Hide cast button'"

[Youtube Music]
build-mode = "apk"
apkmirror-arch = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
